{
 "title": "meli_ps",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estado",
    "query": "SELECT state_name\nFROM address\nORDER BY state_name"
   },
   {
    "name": "cidade",
    "query": "SELECT city_name\nFROM address\nWHERE state_name IN ($estado)\nORDER BY city_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Preço médio por cidade",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT AVG(price) as average_price, a.city_name\nFROM products AS p\nINNER JOIN address a ON a.id = p.city_id\nWHERE a.city_name in ($cidade)\nGROUP BY a.city_name, a.state_name\nORDER BY average_price desc\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Preço total por cidade",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(price) as total_price, a.city_name\nFROM products AS p\nINNER JOIN address a ON a.id = p.city_id\nWHERE a.city_name in ($cidade)\nGROUP BY a.city_name, a.state_name\nORDER BY total_price desc\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Numero de postagens por cidade",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(price) as total_price, a.city_name\nFROM products AS p\nINNER JOIN address a ON a.id = p.city_id\nWHERE a.state_name in ($estado)\nGROUP BY a.city_name, a.state_name\nHAVING COUNT(price) > 4\nORDER BY total_price desc"
    }
   ]
  },
  {
   "title": "Maiores vendedores",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "postagens" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(price) as total_seller_quantity, s.nickname\nFROM products AS p\nINNER JOIN address a ON a.id = p.city_id\nINNER JOIN seller s ON s.id = p.seller_id\nWHERE a.city_name in ($cidade) AND a.state_name IN ($estado)\nGROUP BY s.nickname\nORDER BY total_seller_quantity desc\nLIMIT 10"
    }
   ]
  }
 ]
}